### ISSUE TITLE
Unable to access 'https://github.com/starkandwayne/concourse-tutorial.git/'

### ISSUE THREAD

**Issue by wellyal** [concourse/docs#369]
Following your [tutorial](https://concoursetutorial.com/basics/pipeline-resources/), it seems like the container is being unable to resolve host: github.com. Am I missing something here?

```
run check step: run check step: check: resource script '/opt/resource/check []' failed: exit status 128

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
fatal: unable to access 'https://github.com/starkandwayne/concourse-tutorial.git/': Could not resolve host: github.com
```

**Comment by taylorsilva** [comment]
We did start seeing this our [concourse/dev image](https://hub.docker.com/r/concourse/dev) recently. One of our devs found out it was due to a recent update with [musl](https://git.musl-libc.org/cgit/musl/tree/WHATSNEW#n2223) that was supposed to fix something but caused this problem.

Workaround for us with our dev image is to use the [`concourse/git-resource:ubuntu` image](https://hub.docker.com/r/concourse/git-resource).

That tutorial is community maintained. I noticed it's using v5.6.0. DId you modify the docker-compose.yml or are you using the default one in the tutorial? Just curious how an old image is suddenly having this issue or if you're getting this with a recent image.

---
Reproducible steps

```
$ docker run -it alpine:edge

# apk add curl

# curl https://github.com
<html...

# apk add --upgrade musl
(1/1) Upgrading musl (1.1.24-r9 -> 1.2.1-r0)

# curl https://github.com
curl: (6) Could not resolve host: github.com
```

**Comment by wellyal** [comment]
Hey @taylorsilva thanks for the answer. I am using the default file from tutorial.

```
version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
      PGDATA: /database

  concourse:
    image: concourse/concourse
    command: quickstart
    privileged: true
    depends_on: [concourse-db]
    ports: ["8080:8080"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: Y29uY291cnNlLXdlYgo=
      CONCOURSE_TSA_CLIENT_SECRET: Y29uY291cnNlLXdvcmtlcgo=
```

**Comment by taylorsilva** [comment]
There is definitely something up with that git resource on the `latest` image.

```
root@4e722ce9ba06:/usr/local/concourse/resource-types/git# tar xzf rootfs.tgz -C ./container/
root@4e722ce9ba06:/usr/local/concourse/resource-types/git# cd container/
root@4e722ce9ba06:/usr/local/concourse/resource-types/git/container# chroot .
/ # curl https://github.com
curl: (6) Could not resolve host: github.com
```

As a workaround you can redefine the `git` resource in your pipeline and point it to `concourse/git-resource:ubuntu`

**Comment by taylorsilva** [comment]
simpler reproducible:
```
$ docker run -it concourse/git-resource /bin/bash
bash-5.0# curl https://github.com
curl: (6) Could not resolve host: github.com
```

**Comment by chenbh** [comment]
You should also be able work around it by using the ubuntu image:
```yaml
services:
  ...
  concourse:
    image: concourse/concourse:ubuntu
    command: quickstart
    ...
```

Relevant issue: https://github.com/concourse/concourse/issues/6038
