### ISSUE TITLE
Wrong content in gif regarding output_mapping

### ISSUE THREAD

**Issue by toanju** [concourse/docs#542]
### Describe the bug

In https://concourse-ci.org/exploring-task-input-and-output-scenarios.html#3---mapping-the-names-of-inputs-and-outputs the picture shows the wrong information wrt. the output_mapping. The docs below are fine.

Docs show

```
  - task: create-one-output
    # The task config has the artifact `the-output`
    # output_mapping will rename `the-output` to `demo-disk`
    # in the rest of the job's plan
    output_mapping:
      the-output: demo-disk
```

Gif shows:

```
    output_mapping:
     demo-disk: the-output
```

### Reproduction steps

1. Read
2. Compare
3. D'oh

### Expected behavior

Correct or removed gif
