### ISSUE TITLE
Example of using `registry-image` resource type `defaults` block to provide default `registry_mirror` has issues

### ISSUE THREAD

**Issue by robtaylorsky** [concourse/docs#560]
### Describe the bug

In the [docs here](https://concourse-ci.org/resource-types.html) (under "Overriding default resource types" in the `defaults` section) it shows how you can provide default settings for the `registry-image` resource so that any container images in your pipeline will get fetched from an alternative container registry (*not* hub.docker.com):

```
resource_types:
- name: registry-image
  type: registry-image
  source:
    repository: concourse/registry-image-resource
  defaults:
    registry_mirror:
      host: https://registry.mirror.example.com

resources:
- name: mirrored-image
  type: registry-image
  source:
    repository: busybox
```

There are some issues with this example.

Your pipeline will fetch the `latest` tag of the `concourse/registry-image-resource` container image and then use this image to spin up a `registry-image` resource type container to pull container images in your pipeline. Unfortunately, the `latest` tag for the `concourse/registry-image-resource` image is 4 years old and users can encounter issues - such as errors when trying to authenticate with GCR using JSON credentials.

Updating the `latest` tag or editing the example to include a pinned version might also not be ideal. It's maybe better to fall back on using the version of the `registry-image-resource` image bundled with the Concourse release that's found on the worker.

### Reproduction steps

See above.

### Expected behavior

See above.
